language: ruby
services:
- docker
env:
  - DOCKER_COMPOSE_VERSION=1.4.2
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - cd api
install:
- gem install rails
- mkdir -p ~/api/build/jehenderson/athena/db
before_script:
- docker-compose build
- docker-compose up -d
- sleep 30
- docker ps -a
after_script:
- docker-compose down
