env:
- DOCKER_COMPOSE_VERSION=1.24.1
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin

jobs:
  include:
    - language: python
      install:
      - cd api
      - docker-compose build
      before_script:
      - docker-compose up -d
      - sleep 10
      - docker ps -a
      script:
      - curl localhost://8080 -f
      - python -c "print('Hi from Python!')"
      after_script:
      - docker-compose down

    - language: node_js
      cache:
        directories:
          - node_modules
      install:
      - cd client
      - docker-compose build
      before_script:
      - docker-compose up -d
      - sleep 10
      - docker ps -a
      script:
      - curl localhost://3001 -f
      - node -e "console.log('Hi from NodeJS!')"
      after_script:
      - docker-compose down
