version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  server:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rake db:create && rake db:migrate && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - .:/athena
    ports:
      - "8080:8080"
    depends_on:
      - db
